FROM alpine:3.19

ARG JMETER_VERSION=5.6.3
ENV JMETER_HOME=/opt/apache-jmeter-${JMETER_VERSION}
ENV PATH="${JMETER_HOME}/bin:${PATH}"

RUN apk add --no-cache openjdk17-jre curl bash wget python3 \
 && mkdir -p /opt \
 && curl -L --silent \
    https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz \
    | tar -xzf - -C /opt \
 && mkdir -p /jmeter/results /jmeter/report

WORKDIR /jmeter
