"""
TokenShield — Step 3.3: Device Fingerprint Ban (Redis)
======================================================
Blocks a device fingerprint across ALL sessions, not just the current one.

Why this matters
----------------
Token revocation (Step 1.3) blocks one session.
IP blocking (Step 3.1) blocks one network address.
Device fingerprint banning blocks the physical device —
even if the attacker:
  - Gets a new session token (re-logs in from another account)
  - Switches to a VPN (new IP)
  - Uses a fresh browser tab

A device fingerprint is a SHA-256 hash of:
  screen resolution + timezone + platform + CPU cores +
  canvas fingerprint + WebGL fingerprint + User-Agent (first 100 chars)
This is generated by the frontend JS collector and stored in
BehaviorLog.fingerprint_data by the existing /api/security/threat-detect
endpoint.

Redis key schema
----------------
  ts:fp:{fingerprint_hash}   →  reason string
  TTL: 72 hours (3 days)

Before-request integration
--------------------------
_before_request_hook() extracts the X-Device-Fingerprint header
(set by the frontend on every authenticated request) and checks
it against the Redis banlist before running the 7-signal scorer.
This adds ~0.1ms per request (single Redis EXISTS).

Fallback
--------
If Redis is unavailable, the ban check is skipped (fail open).
The session-level DB revocation still fires.
"""

import json
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger("tokenshield.fingerprint")

FINGERPRINT_PREFIX  = "ts:fp:"
FINGERPRINT_TTL     = 72 * 3600    # 72 hours
FINGERPRINT_HEADER  = "X-Device-Fingerprint"   # set by frontend JS

# ---------------------------------------------------------------------------
# Core ban / check / unban
# ---------------------------------------------------------------------------

def ban_fingerprint(fingerprint: str, reason: str, ttl: int = FINGERPRINT_TTL) -> bool:
    """
    Add a device fingerprint to the Redis banlist.
    Returns True if written, False if Redis is unavailable.
    """
    if not fingerprint or len(fingerprint) < 8:
        return False

    try:
        from app.middleware.redis_client import get_redis
        r = get_redis()
        if r is None:
            return False
        key = FINGERPRINT_PREFIX + fingerprint
        r.setex(key, ttl, reason)
        logger.warning(
            "tokenshield.fingerprint: BANNED fp=%s... reason=%s",
            fingerprint[:12], reason,
        )
        return True
    except Exception as exc:
        logger.error("tokenshield.fingerprint: ban failed — %s", exc)
        return False


def is_fingerprint_banned(fingerprint: str) -> tuple[bool, Optional[str]]:
    """
    Check whether a device fingerprint is banned.
    Returns (banned: bool, reason: str | None).
    Fails open — returns (False, None) if Redis is unavailable.
    """
    if not fingerprint:
        return False, None

    try:
        from app.middleware.redis_client import get_redis
        r = get_redis()
        if r is None:
            return False, None
        reason = r.get(FINGERPRINT_PREFIX + fingerprint)
        if reason:
            return True, reason
        return False, None
    except Exception as exc:
        logger.error("tokenshield.fingerprint: check failed — %s", exc)
        return False, None


def unban_fingerprint(fingerprint: str) -> bool:
    """Remove a device fingerprint from the banlist."""
    try:
        from app.middleware.redis_client import get_redis
        r = get_redis()
        if r is None:
            return False
        deleted = r.delete(FINGERPRINT_PREFIX + fingerprint)
        return bool(deleted)
    except Exception as exc:
        logger.error("tokenshield.fingerprint: unban failed — %s", exc)
        return False


def banlist_stats() -> dict:
    """Return count of currently banned fingerprints."""
    try:
        from app.middleware.redis_client import get_redis
        r = get_redis()
        if r is None:
            return {"available": False, "banned_count": 0}
        keys = r.keys(FINGERPRINT_PREFIX + "*")
        return {"available": True, "banned_count": len(keys)}
    except Exception:
        return {"available": False, "banned_count": 0}


# ---------------------------------------------------------------------------
# Session-linked ban: extract fingerprint from BehaviorLog + ban it
# ---------------------------------------------------------------------------

def ban_session_fingerprint(session_id: int, reason: str) -> tuple[bool, Optional[str]]:
    """
    Look up the most recent device fingerprint stored for a session
    (from BehaviorLog.fingerprint_data written by /api/security/threat-detect),
    then ban it.

    Returns (success: bool, fingerprint: str | None).
    Called by _mitigate() in detection.py when score >= THREAT_THRESHOLD,
    and by the admin manual-revoke endpoint.
    """
    try:
        from app.models import BehaviorLog

        # Most recent log row that has fingerprint_data with a device_fingerprint field
        logs = (
            BehaviorLog.query
            .filter_by(session_id=session_id)
            .filter(BehaviorLog.fingerprint_data.isnot(None))
            .order_by(BehaviorLog.timestamp.desc())
            .limit(20)
            .all()
        )

        fingerprint = None
        for log in logs:
            try:
                data = json.loads(log.fingerprint_data)
                fp   = data.get("device_fingerprint")
                if fp and len(fp) >= 8:
                    fingerprint = fp
                    break
            except Exception:
                continue

        if not fingerprint:
            logger.debug(
                "tokenshield.fingerprint: no device_fingerprint found for sid=%d",
                session_id,
            )
            return False, None

        success = ban_fingerprint(fingerprint, reason)
        return success, fingerprint

    except Exception as exc:
        logger.error("tokenshield.fingerprint: ban_session_fingerprint failed — %s", exc)
        return False, None


# ---------------------------------------------------------------------------
# Extract fingerprint from the current request header
# ---------------------------------------------------------------------------

def get_request_fingerprint() -> Optional[str]:
    """
    Read the X-Device-Fingerprint header from the current Flask request.
    Returns None if header is absent or malformed.
    The frontend JS sets this header on every authenticated API call.
    """
    try:
        from flask import request
        fp = request.headers.get(FINGERPRINT_HEADER, "").strip()
        return fp if len(fp) >= 8 else None
    except Exception:
        return None